export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"
export NPM_CONFIG_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/npm"
export NPM_CONFIG_TMP="${XDG_RUNTIME_DIR:-/run/user/$UID}/npm"
export npm_config_prefix="${XDG_LIB_HOME:-$HOME/.local/lib}/npm"
export PATH="$npm_config_prefix/bin:$PATH"
